INSTALL := /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/install

.PHONY: all install clean

all:
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/LuaJIT-2.1-20240815 && $(MAKE) TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -fno-stack-check' CC=cc MACOSX_DEPLOYMENT_TARGET='14.6' PREFIX=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-cjson-2.1.0.14 && $(MAKE) DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_CMODULE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LUA_MODULE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib CJSON_CFLAGS="-g -fpic" CJSON_LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-signal-0.04 && $(MAKE) DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-redis-parser-0.13 && $(MAKE) DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-rds-parser-0.06 && $(MAKE) DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/nginx-1.27.1 && $(MAKE)

install: all
	mkdir -p $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/
	-cp /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/COPYRIGHT $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/LuaJIT-2.1-20240815 && $(MAKE) install TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -fno-stack-check' CC=cc MACOSX_DEPLOYMENT_TARGET='14.6' PREFIX=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit DESTDIR=$(DESTDIR)
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-cjson-2.1.0.14 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_CMODULE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LUA_MODULE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib CJSON_CFLAGS="-g -fpic" CJSON_LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-signal-0.04 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-redis-parser-0.13 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-rds-parser-0.06 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_INCLUDE_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/luajit-root/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/luajit/include/luajit-2.1 LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib LDFLAGS='-bundle -undefined dynamic_lookup' CC=cc
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-dns-0.23 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-memcached-0.17 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-redis-0.31 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-mysql-0.27 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-string-0.16 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-upload-0.11 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-websocket-0.12 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-lock-0.09 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-lrucache-0.15 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-core-0.1.30 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-upstream-healthcheck-0.08 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-limit-traffic-0.09 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-resty-shell-0.03 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/lua-tablepool-0.03 && $(MAKE) install DESTDIR=$(DESTDIR) LUA_LIB_DIR=/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/lualib INSTALL='$(INSTALL)'
	mkdir -p '$(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/bin/'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/opm-0.0.8 && $(INSTALL) bin/* '$(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/bin/'
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/resty-cli-0.30 && $(INSTALL) bin/* $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/bin/
	cp /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/resty.index $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/
	cp -r /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/pod $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/
	cd /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/build/nginx-1.27.1 && $(MAKE) install DESTDIR=$(DESTDIR)
	mkdir -p $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/site/lualib $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/site/pod $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/site/manifest
	ln -sf /Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/nginx/sbin/nginx $(DESTDIR)/Users/yuanzhaoyi/Develop/dev-openresty/openresty-1.27.1.1/_build/bin/openresty

clean:
#	rm -rf build *.exe *.dll openresty-*
